### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by lloydbenson** [hapijs/isemail#6] opened 2015-09-15 21:19 UTC
npm test fails for me for both 0.10 and v4.  The culprit may be test #12 'isEmail should handle test 6'.

**Comment by skeggse** [comment] 2015-09-15 21:20
Please post the full output from `npm test`.

**Comment by lloydbenson** [comment] 2015-09-15 21:39
[lloyd@laserbeak isemail]$ npm test

> isemail@1.2.0 test /home/lloyd/scm/lloydbenson/isemail
> lab -r console -o stdout -r lcov -o coverage.lcov -a code -L


  
  ...........x......................................
  ..................................................
  ..................................................
  ...............................................

Failed tests:

  12) isEmail should handle test 6:

      actual expected

      90

      Expected 9 to equal specified value

      at /home/lloyd/scm/lloydbenson/isemail/test/isemail.js:127:32


1 of 197 tests failed
Test duration: 1764 ms
Assertions count: 203 (verbosity: 1.03)
No global variable leaks detected
Coverage: 100.00%
Linting results: No issues

**Comment by lloydbenson** [comment] 2015-09-15 21:48
In v0.10.40 I get a little different result:

> isemail@1.2.0 test /home/lloyd/scm/lloydbenson/isemail
> lab -r console -o stdout -r lcov -o coverage.lcov -a code -L


  
  ...........
/home/lloyd/scm/lloydbenson/isemail/node_modules/code/lib/index.js:90
    throw error;
          ^
Error: Expected 9 to equal specified value
    at internals.addMethod.type (/home/lloyd/scm/lloydbenson/isemail/node_modules/code/lib/index.js:199:17)
    at /home/lloyd/scm/lloydbenson/isemail/test/isemail.js:127:32
    at finish (/home/lloyd/scm/lloydbenson/isemail/lib/isemail.js:1304:100)
    at resolveDNS (/home/lloyd/scm/lloydbenson/isemail/lib/isemail.js:1337:107)
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:149:9)
npm ERR! Test failed.  See above for more details.


If its helpful I am running on linux as well but on fedora 21 (a redhat variant).

**Comment by skeggse** [comment] 2015-09-15 21:48
Please wrap those in code fences (```)

**Comment by skeggse** [comment] 2015-09-15 21:49
Also please post the output from `node -v && node -e "require('dns').resolveMx('io.', console.log);"`

**Comment by lloydbenson** [comment] 2015-09-15 22:00
```
v0.10.40
{ [Error: queryMx ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'queryMx' }
```

**Comment by skeggse** [comment] 2015-09-17 15:25
The only thing that I can think of is that you have a local DNS cache that's incorrectly handling the `io` TLD DNS records. I can't reproduce this on a number of systems, including the mentioned Fedora version, so I'm going to close this. If you can reproduce this on another system on a different network, I'll take another look, but there's not much I can do with this.

**Closed by skeggse** 2015-09-17 15:25 UTC

**Comment by lloydbenson** [comment] 2015-09-17 15:42
Is there a simple DNS command you can break this down to so that can track this down?  A dig, or host like command would be helpful to debug this but I don't quite understand what this test is trying to do.  Is it trying to do a mx (mail record) lookup on a domain called 'io.'?

**Comment by skeggse** [comment] 2015-09-17 15:44
Yep. [`io`](https://en.wikipedia.org/wiki/.io) is the country TLD for the British Indian Ocean Territory, and is one of the few top-level domains to host its own MX record. You can verify this with your favorite online DNS query website.

**Comment by lloydbenson** [comment] 2015-09-17 16:12
Thanks.  This is helpful.  I confirmed with other users they can indeed a record so I have narrowed it down my ISP most likely.  Thanks.  For those that may run into this the command "dig -t mx io" should return a valid record.
